<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\InventoryManagement.Domain\InventoryManagement.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Mapster" Version="9.0.0-pre01" />
      <PackageReference Include="StackExchange.Redis" Version="2.9.32" />
    </ItemGroup>

</Project>
